[package]
name = "ca_collide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.15", features=["webgpu"]}
bevy_egui = "0.31.1"
bevy_embedded_assets = "0.12.0"
